version: '3.1'
services:

  tomcat:
    build:
      context: ./../tomcat/
      dockerfile: Dockerfile
    image: test-tomcat:latest
    ports:
      - "11111:8080"

  nginx:
    build:
      context: ./nginx-config
      dockerfile: Dockerfile
    image: test-nginx:latest
    ports:
      - "80:80"
      - "443:443"
